Site/Site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Указание на папку с файлами, загружаемые с админки

Site/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.BlogView.as_view(), name='home'),  # Адрес главной страницы
    path('about.html', views.AboutView.as_view(), name='about'),  # Адрес страницы обо мне
    path('contact.html', views.ContactView.as_view(), name='contact'),  # Адрес страницы контактов
    path('<slug:slug>/', views.SingleView.as_view(), name='single'),  # Адрес статьи
    path('work.html', views.WorkView.as_view(), name='work'),  # Адрес страницы о работах
    path('review/<int:pk>/', views.AddReview.as_view(), name='add_review'),  # Адреес для отправки формы отзывов о статье
    path('/feedback/', views.AddFeedback.as_view(), name='add_feedback'),  # Адрес для отправки формы отзывов о работе
]

Site/blog/models.py
from django.db import models
from datetime import date
from django.urls import reverse


# Модель для новостей
class News(models.Model):
    """Новости"""
    title = models.CharField("Заголовок", max_length=150)
    name = models.CharField("Автор", max_length=100)
    description = models.TextField("Описание")
    text = models.TextField("Текст новости")
    date = models.DateField("Дата публикации", default=date.today)
    url = models.SlugField(max_length=160, unique=True)

    # Функция, возвращающая url новости
    def get_absolute_url(self):
        return reverse('single', kwargs={'slug': self.url})

    def __str__(self):
        return self.title

    # Метаданные
    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"


# Модель для отзывов
class Reviews(models.Model):
    """Отзывы"""
    name = models.CharField("Имя", max_length=100)
    email = models.EmailField()
    text = models.TextField("Сообщение", max_length=5000)
    news = models.ForeignKey(News, verbose_name="Новость", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.news}"

    # Метаданные
    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


# Модель для языков
class Language(models.Model):
    """Языки программирования"""
    name = models.CharField('Название языка', max_length=50)

    def __str__(self):
        return self.name

    # Метаданные
    class Meta:
        verbose_name = 'Язык программирования'
        verbose_name_plural = 'Языки программирования'


# Модель для работ
class Works(models.Model):
    """Мои работы"""
    name = models.CharField("Название", max_length=50)
    skills = models.ForeignKey(Language, verbose_name='Язык программирования', on_delete=models.CASCADE)
    duration = models.CharField("Количество затраченного времени", max_length=10)
    url = models.CharField('Url', max_length=160)
    about = models.CharField("О проекте", max_length=150)
    image = models.ImageField('Картинка', upload_to='works/', default='static/images/default.jpg')

    def __str__(self):
        return self.name

    # Метаданные
    class Meta:
        verbose_name = 'Моя работа'
        verbose_name_plural = 'Мои работы'


# Модель для отзывов о работе
class Feedback(models.Model):
    """Отзывы о работе"""
    name = models.CharField("Имя", max_length=50)
    email = models.EmailField()
    text = models.TextField("Отзыв", max_length=150)
    work = models.CharField("Место работы", max_length=50)

    def __str__(self):
        return self.name

    # Метаданные
    class Meta:
        verbose_name = "Отзыв о работе"
        verbose_name_plural = "Отзывы о работе"

Site/blog/forms.py
from django import forms

from .models import Reviews, Feedback


# Класс формы отзывов о статье
class ReviewForm(forms.ModelForm):
    """Форма отзывов"""
    class Meta:
        model = Reviews  # Модель, от которой строится форма
        fields = ('name', 'email', 'text')  # Требуемые поля из модели


# Класс формы отзывов о работе
class FeedbackForm(forms.ModelForm):
    """Форма отзыва о работе"""
    class Meta:
        model = Feedback  # Модель, от которой строится форма
        fields = ('name', 'email', 'work', 'text')  # Требуемые поля из модели

Site/blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View

from .forms import ReviewForm, FeedbackForm
from .models import News, Works, Feedback


# Класс отображения index.html
class BlogView(View):

    def get(self, request):
        news = News.objects.all()
        return render(request, 'index.html', {'news': news})


# Класс отображения about.html
class AboutView(View):

    def get(self, request):
        return render(request, 'about.html')


# Класс отображения contact.html
class ContactView(View):

    def get(self, request):
        feedbacks = Feedback.objects.all()
        return render(request, 'contact.html', {'feedbacks': feedbacks})


# Класс отображения work.html
class SingleView(View):

    def get(self, request, slug):
        news = News.objects.get(url=slug)
        return render(request, 'single.html', {"news": news})


# Класс отображения work.html
class WorkView(View):

    def get(self, request):
        works = Works.objects.all()
        return render(request, 'work.html', {'works': works})


# Класс для отправки отзывов о статье
class AddReview(View):

    def post(self, request, pk):
        form = ReviewForm(request.POST)  # Заполнение формы из формы на сайте
        new = News.objects.get(id=pk)  # Из модели берём статью по id
        if form.is_valid():  # Проверка на валидность
            form = form.save(commit=False)  # Приостановка сохранения формы
            form.news = new  # Указываем статью, к которой нужно привязаться
            form.save()  # Заносим данные в базу
        return redirect(new.get_absolute_url())  # Перенаправление обратно на статью


# Класс для отправки отзывов о работе
class AddFeedback(View):

    def post(self, request):
        form = FeedbackForm(request.POST)  # Заполнение формы из формы на сайте
        if form.is_valid():  # Проверка на валидность
            form = form.save(commit=False)  # Приостановка сохранения формы
            form.save()  # Заносим данные в базу
        return redirect('contact')  # Перенаправление на обратно на contact.html

Site/templates/about.html
{% extends 'base.html' %}

{% block head %}About Me{% endblock head %}

{% block title %}About Me{% endblock title %}

{% block conteiner %}<a href="contact.html"><i class="icon-envelope"></i></a>{% endblock conteiner %}

{% block content %}
<div class="col-md-12 blog-post">


    <!-- My Intro Start -->
    <div class="post-title margin-bottom-30">
        <h1>Hi, I am <span class="main-color">Vladislav Yurashevich</span></h1>

        <ul class="knowledge">
            <li class="bg-color-1">Backend developer</li>
            <li class="bg-color-4">Student BSUIR</li>
            <li class="bg-color-6">Freelancer</li>
        </ul>

    </div>
    <!-- My Intro End -->


    <p>Greetings to my first Django site! I am <b>Vladislav Yurashevich</b>, a second year student at BSUIR.
        I'm 19 years old. Ever since high school, I began to understand that my profession would be related
        to the Internet, computers and programming. At the age of 15, I began to be interested in programming
        languages, computer design. Thanks to this, I didn't have to think about where to go, since the road
        to BSUIR was paved for me. The first programming language was <b>Python</b>, so I looked for areas where it
        is used and found - <b>backend development</b>. This is my first work with the Django framework and in the
        future I plan to improve this site.
    </p>


    <!-- My Skills Start -->
    <div class="post-title">
        <h1>My <span class="main-color">Skills</span></h1>
    </div>

    <div class="list list-style-2 margin-top-30">
        <ul>
            <li>Python</li>
            <li>C++</li>
            <li>HTML</li>
            <li>CSS</li>
            <li>Backend development</li>
        </ul>
    </div>
    <!-- My Skills End -->

</div>
{% endblock content %}

Site/templates/base.html
<!-- Основной шаблон для сайта -->
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <!-- Meta Tag -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>{% block head %}{% endblock head %}</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon/favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="144x144" type="image/x-icon"
          href="{% static 'images/favicon/apple-touch-icon.png' %}">

    <!-- All CSS Plugins -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/plugin.css' %}"><!-- css/plugin.css -->

    <!-- Main CSS Stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"><!-- css/style.css -->

    <!-- Google Web Fonts  -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:400,300,500,600,700">


    <!-- HTML5 shiv and Respond.js support IE8 or Older for HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>

<body>


<!-- Preloader Start -->
<div class="preloader">
    <div class="rounder"></div>
</div>
<!-- Preloader End -->


<div id="main">
    <div class="container">
        <div class="row">


            <!-- About Me (Left Sidebar) Start -->
            <div class="col-md-3">
                <div class="about-fixed">

                    <div class="my-pic">
                        <img src="{% static 'images/name2.jpg' %}" alt="">
                        <a href="javascript:void(0)" class="collapsed" data-target="#menu" data-toggle="collapse"><i
                                class="icon-menu menu"></i></a>
                        <div id="menu" class="collapse">
                            <ul class="menu-link">
                                <li><a href="/about.html">About</a></li>
                                <li><a href="/work.html">Work</a></li>
                                <li><a href="/contact.html">Contact</a></li>
                            </ul>
                        </div>
                    </div>


                    <div class="my-detail">

                        <div class="white-spacing">
                            <h1>Vladislav Yurashevich</h1>
                            <span>Backend developer</span>
                        </div>

                        <ul class="social-icon">
                            <li><a href="https://vk.com/vladyurashevich" target="_blank" class="vk"><i class="fa fa-vk"></i></a></li>
                            <li><a href="https://www.instagram.com/vlad.urashevich/" target="_blank" class="instagram"><i class="fa fa-instagram"></i></a></li>
                            <li><a href="https://www.linkedin.com/in/%D0%B2%D0%BB%D0%B0%D0%B4%D0%B8%D1%81%D0%BB%D0%B0%D0%B2-%D1%8E%D1%80%D0%B0%D1%88%D0%B5%D0%B2%D0%B8%D1%87-559138224/" target="_blank" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="https://github.com/VladYura" target="_blank" class="github"><i class="fa fa-github"></i></a></li>
                        </ul>

                    </div>
                </div>
            </div>
            <!-- About Me (Left Sidebar) End -->


            <!-- Blog Post (Right Sidebar) Start -->
            <div class="col-md-9">
                <div class="col-md-12 page-body">
                    <div class="row">


                        <div class="sub-title">
                            <h2>{% block title %} {% endblock title %}</h2>
                            {% block conteiner %} {% endblock conteiner %}
                        </div>


                        <div class="col-md-12 content-page">
                            {% block content %}

                            {% endblock content %}
                        </div>

                    </div>

                </div>


                <!-- Footer Start -->
                <div class="col-md-12 page-body margin-top-50 footer">
                    <footer>
                        <ul class="menu-link">
                            <li><a href="/">Home</a></li>
                            <li><a href="/about.html">About</a></li>
                            <li><a href="/work.html">Work</a></li>
                            <li><a href="/contact.html">Contact</a></li>
                        </ul>

                        <p>© Copyright 2016 DevBlog. All rights reserved</p>


                        <!-- UiPasta Credit Start -->
                        <div class="uipasta-credit">Design By <a href="http://www.uipasta.com"
                                                                 target="_blank">UiPasta</a></div>
                        <!-- UiPasta Credit End -->


                    </footer>
                </div>
                <!-- Footer End -->


            </div>
            <!-- Blog Post (Right Sidebar) End -->

        </div>
    </div>
</div>


<!-- Back to Top Start -->
<a href="#" class="scroll-to-top"><i class="fa fa-long-arrow-up"></i></a>
<!-- Back to Top End -->


<!-- All Javascript Plugins  -->
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/plugin.js' %}"></script>

<!-- Main Javascript File  -->
<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>


</body>
</html>

Site/templates/contact.html
{% extends 'base.html' %}

{% block head %}Contact Me{% endblock head %}

{% block title %}Contact Me{% endblock title %}

{% block conteiner %}<a href="/"><i class="icon-home"></i></a>{% endblock conteiner %}

{% block content %}
<div class="col-md-12 blog-post">


    <!-- Testimonials Start -->
    <div class="post-title margin-top-50">
        <h2>I hope you've checked <a href="work.html" data-toggle="tooltip"
                                     data-placement="top" title="Check out my work.">my
            work</a>, Let's take a look on what other clients said about my work.</h2>
    </div>


    <div class="row">
        {% for feedback in feedbacks %}
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="testimonial-content">
                <p>{{ feedback.text }}</p>
            </div>

            <div class="testimonial-client-info">

                <div class="testimonial-client client-thumb">
                    <img src="images/testimonial/1.png" alt="">
                </div>

                <div class="client-text">
                    <div class="client-name">{{ feedback.name }}</div>
                    <span>{{ feedback.work }}</span>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- Testimonials  End -->

    <div class="col-md-12 text-center">
        <a href="javascript:void(0)" id="load-more-post" class="load-more-button">Load</a>
        <div id="post-end-message"></div>
    </div>

    <!-- Contact Me Start -->
    <div class="post-title margin-top-70">
        <h1>Contact <span class="main-color">Me</span></h1>
    </div>


    <div class="row">

        <div class="col-md-4 col-sm-4">
            <div class="contact-us-detail">
                <i class="icon-screen-smartphone color-6"></i>
                <p>+375 (44) 773-79-95</p>
            </div>
        </div>

        <div class="col-md-4 col-sm-4">
            <div class="contact-us-detail">
                <i class="icon-envelope-open color-5"></i>
                <p>vlad.yurashevich02@mail.ru</p>
            </div>
        </div>

        <div class="col-md-4 col-sm-4">
            <div class="contact-us-detail">
                <i class="icon-clock color-3"></i>
                <p>Mon - Fri 09:00 – 18:00</p>
            </div>
        </div>

    </div>

    <div class="post-title margin-top-70">
        <h1>Leave <span class="main-color">Feedback</span></h1>
    </div>

    <div class="row margin-top-30">
        <div class="col-md-12">

            <div class="row">
                <form action="{% url 'add_feedback' %}" method="post">
                    {% csrf_token %}<!--Токен защиты-->
                    <div class="col-sm-6">
                        <div class="form-group">
                            <input type="text" id="name" class="form-control" name="name"
                                   placeholder="Your Name">
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <input type="email" id="email" class="form-control" name="email"
                                   placeholder="Your Email">
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group">
                            <input type="text" id="website" class="form-control" name="work"
                                   placeholder="Where are you work?">
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="textarea-message form-group">
                            <textarea id="message" class="textarea-message form-control" name="text"
                                      placeholder="Your Message" rows="5"></textarea>
                        </div>
                    </div>

                    <div class="text-center">
                        <button type="submit" class="load-more-button">Send</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
    <!-- Contact Me End -->


</div>
{% endblock content %}

Site/templates/feedback.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Site/templates/index.html
{% extends 'base.html' %}

{% block head %}My Blog{% endblock head %}

{% block title %}My Blog{% endblock title %}

{% block conteiner %}<a href="contact.html"><i class="icon-envelope"></i></a>{% endblock conteiner %}

{% block content %}
<!-- Blog Post Start -->
{% for new in news %}
<div class="col-md-12 blog-post">
    <div class="post-title">
        <a href="{% url 'single' new.url %}"><h1>{{ new.title }}</h1></a>
    </div>
    <div class="post-info">
        <span>{{ new.date }} / by <a href="#" target="_blank">{{ new.name }}</a></span>
    </div>
    <p>{{ new.description }}</p>
    <a href="{% url 'single' new.url %}" class="button button-style button-anim fa fa-long-arrow-right"><span>Читать больше</span></a>
</div>
{% endfor %}
<!-- Blog Post End -->


<div class="col-md-12 text-center">
    <a href="javascript:void(0)" id="load-more-post" class="load-more-button">Load</a>
    <div id="post-end-message"></div>
</div>
{% endblock content %}

Site/templates/single.html
{% extends 'base.html' %}

{% block head %}{{ news.title }}{% endblock head %}

{% block title %}Back Home{% endblock title %}

{% block conteiner %}<a href="/"><i class="icon-home"></i></a>{% endblock conteiner %}

{% block content %}
<div class="col-md-12 blog-post">


    <!-- Post Headline Start -->
    <div class="post-title">
        <h1>{{ news.title }}</h1>
    </div>
    <!-- Post Headline End -->


    <!-- Post Detail Start -->
    <div class="post-info">
        <span>{{ news.date }} / by <a href="#" target="_blank">{{ news.name }}</a></span>
    </div>
    <!-- Post Detail End -->


    <p>{{ news.text }}</p>





    <!-- Post Comment (Disqus) Start -->
    <div id="comment" class="comment">
        <h3>Discuss about post</h3>


        <!-- Disqus Code Start  (Please Note: Disqus will not be load on local, You have to upload it on server.)-->
        <div class="row margin-top-30">
            <div class="col-md-12">

                <div class="row">
                    <form action="{% url 'add_review' news.id %}" method="post" id="formReview">
                        {% csrf_token %}<!--Токен защиты-->
                        <div class="col-sm-6">
                            <div class="form-group">
                                <input type="text" id="name" class="form-control" name="name"
                                       placeholder="Your Name">
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <input type="email" id="email" class="form-control" name="email"
                                       placeholder="Your Email">
                            </div>
                        </div>

                        <div class="col-sm-12">
                            <div class="textarea-message form-group">
                                <textarea id="message" class="textarea-message form-control" name="text"
                                          placeholder="Your Message" rows="5"></textarea>
                            </div>
                        </div>


                        <div class="text-center">
                            <button type="submit" class="load-more-button">Send</button>
                        </div>

                    </form>
                    {% for review in news.reviews_set.all %}
                    <div class="about-author margin-top-70 margin-bottom-50">

                        <div class="picture">
                            <img src="images/blog/author.png" class="img-responsive" alt="">
                        </div>

                        <div class="c-padding">
                            <h3>
                                {{ review.name }}
                            </h3>
                            <p>
                                {{ review.text }}
                            </p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- Disqus Code End -->

    </div>
    <!-- Post Comment (Disqus) End -->


</div>
{% endblock content %}

Site/templates/work.html
{% extends 'base.html' %}
{% load static %}
{% block head %}My Portfolio{% endblock head %}

{% block title %}My Portfolio{% endblock title %}

{% block conteiner %}<a href="contact.html"><i class="icon-envelope"></i></a>{% endblock conteiner %}

{% block content %}
<div class="col-md-12 blog-post">


    <!-- Intro Start -->
    <div class="post-title margin-bottom-30">
        <h1>Let's take a look on <span class="main-color">My Work</span></h1>
    </div>
    <!-- Intro End -->


    <!-- Portfolio Start -->
    <div>

        {% for work in works %}
        <!-- Portfolio Detail Start -->
        <div class="row portfolio">
            <div class="col-sm-6 custom-pad-1">
                <img src="{{ work.image.url }}" class="img-responsive" alt="">
            </div>


            <div class="col-sm-6 custom-pad-2">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <tbody>

                        <tr>
                            <td><b>Title</b></td>
                            <td>{{ work.name }}</td>
                        </tr>

                        <tr>
                            <td><b>Skills</b></td>
                            <td>{{ work.skills }}</td>
                        </tr>

                        <tr>
                            <td><b>Duration</b></td>
                            <td>{{ work.duration }}</td>
                        </tr>

                        <tr>
                            <td><b>Url</b></td>
                            <td><a href="{{ work.url }}">GitHub</a>
                            </td>
                        </tr>

                        <tr>
                            <td><b>About Project</b></td>
                            <td>{{ work.about }}</td>
                        </tr>

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
        <!-- Portfolio Detail End -->
        {% endfor %}

    </div>
    <!-- Portfolio End -->


</div>

<div class="col-md-12 text-center">
    <a href="javascript:void(0)" id="load-more-portfolio" class="load-more-button">Load</a>
    <div id="portfolio-end-message"></div>
</div>
{% endblock content %}